baseURL: 'http://sukumar.pages.dev'
languageCode: 'en-us'
title: 'Sukumar Patel'
theme:  "hugo-profile"

relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "abc"
  category: "categories"

enableEmoji: true

# menus
# Menus:
#   main:
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2
    
params:
  version: 3
  customCSS: false

  # favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Sukumar Patel"
  namecolor: 6c757d
  profession: "Software Professional"
  hitext: "Hello, I'm"
  linkedin: "https://www.linkedin.com/in/sukumarpatel/"

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "mailto://sukumar.patel@gmail.com"
      name: GMail

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm a software professional with 16+ years of experience in designing and developing applications using Java and Azure based technologies."
  descripe_l2_person: "I am looking for a senior leadership role in the field of Information Technology in a reputed financial technology firm."
  skills:
    - name: Azure 
      percentage: 85
    - name: Azure DevOps
      percentage: 70
    - name: Java
      percentage: 75
    - name: Oracle
      percentage: 80
    - name: Linux
      percentage: 65

  # Experience
  disable_experience: false
  experience:
    - company: "MSCI"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Vice President"
      startdate: Sep 2013
      enddate: present
      featuredpoints:
        - point: Leading the Azure DevOps transformation in Data Technology.
        - point: Designed migration strategies for application migration from on-prem to Azure.
        - point: Designed and implemented migration strategy from on-prem VM’s to AKS on Azure.
    - company: "Nomura"
      role: "Associate"
      startdate: Aug 2009
      enddate: Sep 2013
      featuredpoints:
        - point: Technical lead for the Indian team managing the Hong Kong, Singapore and Japan equities trade settlement system.
        - point: Took complete ownership of the settlement systems in a gradual transition from Hong Kong to India.
        - point: Extensive exposure to Oracle and Unix server migration and DR setup
    - company: "TCS"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "ASE"
      startdate: Feb 2006
      enddate: Aug 2009
      featuredpoints:
        - point: Worked on multiple applications for GE Aviation.
        - point: Worked on and explored Spring, Struts, JSF and Grails
        - point: Gained exposure to working with Oracle databses and supporting systems in production

  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Computer Science & Engineering"
      university: "Utkal university"
      startedyear: "2001"
      graduation: "2005"
    - degree: "12th"
      branch: "Science"
      university: "ISC"
      startedyear: "1999"
      graduation: "2001"
    - degree: "10th"
      branch: "Science"
      university: "ICSE"
      startedyear: "1988"
      graduation: "1999"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - point: 14+ years of experience in developing Java based software design and development
    - point: 3+ years of experience of designing and architecting solutions using various Azure technologies,
    - point: 2+ years of leading the Azure DevOps transformation for Data Technology.
    - point: 2+ years of designing and implementing solutions on Azure Kubernetes Services
    - point: Extensive experience of working on database table design, high volume data extraction and loading.
    - point: 11+ years of experience in Equities reference and market data, and trade settlements
    - point: Good understanding of Azure, Unix and Oracle infrastructure
    - point: Experienced in handling servers and technology migration
    
  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "sukumar.patel@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
